[package]
name = "sui-pet-evolution"
version = "0.0.1"
edition = "2024"


[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
sui_pet_evolution = "0x0"
sui = "0x2"
